### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by AdamYLiang** [FooAl/Kaos#1]
- [x] Initialize git repo in project folder 
- [x] Properly format MVP list to have bullet points with what constitutes a completed MVP. Check the sample here [https://github.com/appacademy/bluebird/wiki/mvp-list](url)

Let me know if you any questions!

**Comment by FooAl** [comment]
Restructured project folder
Properly formatted MVP list

**Comment by AdamYLiang** [comment]
Nice changes, just one more:
- [ ] Add estimated time for completion for each MVP

**Comment by FooAl** [comment]
Added estimated times for each MVP
