### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by AdamYLiang** [FooAl/Kaos#2]
**Users**
- [x] Discord users are able to change their username in servers but they all have a unique discord_id.

**Messages/Channels/Join Tables**
- [x] Underneath the table list out what tables the foreign keys reference.

**Misc**
- [x] Consider making friends and voice channels as bonus tables

Let me know if you have any questions.

**Comment by FooAl** [comment]
Added a nickname join table to allow a user to have different nicknames on different servers
Added foreign key references
Added roles as a bonus table

**Comment by AdamYLiang** [comment]
Good changes, here are a couple more and it should be good to go:
- [ ] Optional detail for `profile_icon_url`, `role_permissions`, and `user_alias`.
- [ ] Consider adding roles and roles join table as a bonus

**Comment by FooAl** [comment]
Added optional for the empty rows
Marked role and role join table as bonuses
