### ISSUE TITLE
Sample State 

### ISSUE THREAD

**Issue by AdamYLiang** [FooAl/Kaos#3]
- [x] Should have `UI` reducer for ui related information (modals, etc.)
- [x] Should have `session` reducer to keep track of currently logged in user
- [x] Should have `errors` reducer to store errors from the back end

**Users**
- [x] Only show relevant data for user that is currently logged in

**Messages**
- [x] Should keep track of when they were created 

**Servers**
- [x] Might be helpful to keep track of a default channel for basic invites (general channel for example)

**Channels**
- [x] Should keep track of what server they belong to 

Let me know if you have any questions or want to talk about these!

**Comment by FooAl** [comment]
Added UI, session and error reducer information
Users only shows which messages belong to the current user; I believe that you should be able to see other user's roles, profile icons and their nickname
Added messages recording when they were made
Added a default channel to servers
Channels can only be accessed through the server they're in, so I believe that they don't need to know which server it exists on

**Comment by AdamYLiang** [comment]
Looks good, as for the channels that makes sense. It might be helpful to store it in the state if you ever need to reference it but we'll see as we build out the project.
