### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by AdamYLiang** [FooAl/Kaos#4]
- [x] Editing and deleting channels/messages id do not need reference to servers since you can look them up by ID. 
- [x] Messages can be fetched either through the specific message ID or by nesting it underneath a channel. Shouldn't have to go through a server to figure out messages since we can use associations to get it if need be.

**Comment by FooAl** [comment]
Removed references to servers from editing and deleting channels/messages
Nested messages only through channels rather than servers then channels
Added /edit to all the editing routes

**Comment by AdamYLiang** [comment]
- [ ] Need a `POST` for messages.

**Comment by FooAl** [comment]
Added `POST` for messages

**Comment by AdamYLiang** [comment]
Nice work!
