### ISSUE TITLE
Frontend Routes

### ISSUE THREAD

**Issue by AdamYLiang** [FooAl/Kaos#5]
- [x] Should have a route for splash page, `/`
- [x] Should have routes for logging in and signing up 
- [x] Discord has a `/me` route for when you are logged in and not on a channel, consider adding this as well
- [x] Discord displays the channel-server relationship as `/channel/:server_id/:channel_id`
- [x] Messages don't need a front end route since they will be fetched from the DB and displayed in the component of a chatroom. 

We don't need many routes for front end of Discord since it just filters between channels and servers.

**Comment by FooAl** [comment]
Added splash page at /
Added routes for login and signup
added /me route when not looking at a channel
changed channel-server route
Removed messages routes

**Comment by AdamYLiang** [comment]
Looks good!
