### ISSUE TITLE
User Auth MVP

### ISSUE THREAD

**Issue by AdamYLiang** [FooAl/Kaos#6]
- [x] Splash page should not say `Login` at the top if a user is logged in. Also change the `Demo User` if so to prevent another POST request. Same goes for the footer at the bottom. 

**CSS**
- [x] Splash page should have background covering entire page. 
- [x] Create own logo to use throughout site 
- [x] Slightly more margin at the top of the splash page 
- [x] `Need an account` and `Register` for the session form should be flush to the left like original app. 

Let me know if you have any questions!

**Comment by FooAl** [comment]
Addressed most of the issues; the logo will be made eventually one night.

**Comment by FooAl** [comment]
Added custom logo
