### ISSUE TITLE
Channel MVP

### ISSUE THREAD

**Issue by AdamYLiang** [FooAl/Kaos#7]
- [x] Remove debuggers on heroku
- [x] Upon login from a new browser, the channels will not populate and a 401 is shown in the console. 
- [x] Strange bug where incognito windows will automatically log users into test demo. Once a user has failed to log in, the app will not work even if you login/logout. 

**CSS**
- [x] Text next to `#` of button should be a bit more centered
- [x] Message input field should be slightly higher

**Comment by FooAl** [comment]
Fixed the issues
